layout_spectrum: 0.9886030438356102
typography_spectrum: 0.6854295248631388
color:
  brandStrength: 0.4812026000581682
  lightness: 0.2457027775235474
  saturation: 0.049694621469825506
  rhythmicContrast: 0.8451872651930898
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
name: The DJ Music Studio
navigation:
  - name: Facebook Page
    url: 'https://www.facebook.com/TheDJMusicStudio/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/DJMusicStudio'
    type: external
  - name: SoundCloud
    url: 'https://soundcloud.com/djmusicstudio'
    type: external
title: 'We made it, but there''s still more to be done.'
description: 'We''ve come this far, we can''t quit now.'
