layout_spectrum: 0.11479270597919822
typography_spectrum: 0.785836742259562
color:
  brandStrength: 0.5038747966755182
  lightness: 0.8205293270293623
  saturation: 0.22461150377057493
  rhythmicContrast: 0.9327805270440876
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
name: The DJ Music Studio
navigation:
  - name: Facebook Page
    url: 'https://www.facebook.com/TheDJMusicStudio/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/DJMusicStudio'
    type: external
  - name: SoundCloud
    url: 'https://soundcloud.com/djmusicstudio'
    type: external
title: 'We made it, but there''s still more to be done.'
description: 'We''ve come this far, we can''t quit now.'
